### ISSUE TITLE
Generate an HTML Page.

### ISSUE THREAD

**Issue by mavidser** [thomshutt/infinite-monkeys#1]
This is awesome, but it'd be more accessible if it generated a single HTML document. 

Even a compiled markdown document would suffice, given that the source files are already in markdown.

**Comment by thomshutt** [comment]
There is actually one being generated already:

https://github.com/thomshutt/infinite-monkeys/tree/master/output

But I'll leave this open until I've set up a gh-pages branch

**Comment by thomshutt** [comment]
Done - I've added a link in the README.
