### ISSUE TITLE
addition

### ISSUE THREAD

**Issue by nickdesaulniers** [thomshutt/infinite-monkeys#4]
I really like this particular comment.  It helps put things in perspective for young "wantrepreneurs."

https://news.ycombinator.com/item?id=9339307

**Comment by thomshutt** [comment]
That's a very reassuring list, would you be able to format it and submit a pull request?

**Comment by nickdesaulniers** [comment]
Will do.  Maybe a separate issue; would it be possible to link back to the original quote?
